// <auto-generated />
using System;
using ManageGateway.Persistence.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManageGateway.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220317060340_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ManageGateway.Domain.Models.Device", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GatewaySerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UID");

                    b.HasIndex("GatewaySerialNumber");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            UID = "03a40e3a-be03-4f28-9b6c-cf8e0f4a92e9",
                            CreatedDate = new DateTime(2012, 3, 17, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7279),
                            GatewaySerialNumber = "DQzrzFZZ",
                            Status = 1,
                            Vendor = "IBM"
                        },
                        new
                        {
                            UID = "a991adf0-c8de-4434-bbcf-0bcf850a1a98",
                            CreatedDate = new DateTime(2001, 10, 17, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7333),
                            GatewaySerialNumber = "DQzrzFZZ",
                            Status = 1,
                            Vendor = "SAMSUNG"
                        },
                        new
                        {
                            UID = "c4f14cf8-009c-40e2-b836-dfb913dba481",
                            CreatedDate = new DateTime(2006, 9, 17, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7340),
                            GatewaySerialNumber = "DQzrzFZZ",
                            Status = 0,
                            Vendor = "APPLE"
                        },
                        new
                        {
                            UID = "2cd05870-18d2-40cb-8f6c-9e15e597ca6a",
                            CreatedDate = new DateTime(2001, 12, 17, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7346),
                            GatewaySerialNumber = "BGVCDTZA",
                            Status = 1,
                            Vendor = "MICROSOFT"
                        },
                        new
                        {
                            UID = "76f928f5-3d01-4ae6-853e-c7b37eba70dc",
                            CreatedDate = new DateTime(2010, 1, 17, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7351),
                            GatewaySerialNumber = "BGVCDTZA",
                            Status = 1,
                            Vendor = "XBOX"
                        },
                        new
                        {
                            UID = "55012c37-8558-429b-97ec-b7d548ba9360",
                            CreatedDate = new DateTime(2001, 10, 27, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7357),
                            GatewaySerialNumber = "BGVCDTZA",
                            Status = 0,
                            Vendor = "PLAY STATION"
                        },
                        new
                        {
                            UID = "e71cbf4b-e654-4ddf-8ab7-f8e0a0048a91",
                            CreatedDate = new DateTime(1996, 7, 27, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7365),
                            GatewaySerialNumber = "BGVCDTZA",
                            Status = 1,
                            Vendor = "LENOVO"
                        },
                        new
                        {
                            UID = "ef7cd65a-b263-4496-ace0-5fcf9f1fc54a",
                            CreatedDate = new DateTime(2001, 10, 27, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7371),
                            GatewaySerialNumber = "BGVCDTZA",
                            Status = 1,
                            Vendor = "PANASONIC"
                        },
                        new
                        {
                            UID = "b3469b25-2015-48dc-a357-e52396fa6bf0",
                            CreatedDate = new DateTime(1998, 10, 18, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7377),
                            GatewaySerialNumber = "5jTocfWo",
                            Status = 0,
                            Vendor = "APPLE TV"
                        },
                        new
                        {
                            UID = "51b9386e-8d28-4d98-a1ef-f3fc536cd172",
                            CreatedDate = new DateTime(2019, 7, 18, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7386),
                            GatewaySerialNumber = "5jTocfWo",
                            Status = 1,
                            Vendor = "APPLE WATCH"
                        },
                        new
                        {
                            UID = "f7276d90-21b1-4395-844c-600b120ee17b",
                            CreatedDate = new DateTime(1996, 10, 27, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7392),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 1,
                            Vendor = "HP"
                        },
                        new
                        {
                            UID = "b1284ada-7fe9-4984-902b-363cd3ea9848",
                            CreatedDate = new DateTime(2002, 2, 27, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7398),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 0,
                            Vendor = "PRINTER"
                        },
                        new
                        {
                            UID = "152c1302-6ebb-40b2-881d-ff1454a15612",
                            CreatedDate = new DateTime(2011, 10, 27, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7404),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 1,
                            Vendor = "HDD"
                        },
                        new
                        {
                            UID = "cd0598c0-0bf0-4a22-94e1-011895510f03",
                            CreatedDate = new DateTime(2001, 7, 2, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7410),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 1,
                            Vendor = "SSD"
                        },
                        new
                        {
                            UID = "15a46dbc-e86a-4511-8c78-59608b2333da",
                            CreatedDate = new DateTime(2011, 1, 27, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7416),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 0,
                            Vendor = "THOSIBA"
                        },
                        new
                        {
                            UID = "a7a82e27-3fce-4d41-a9f3-16e72d71648a",
                            CreatedDate = new DateTime(2002, 8, 27, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7422),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 1,
                            Vendor = "ACER"
                        },
                        new
                        {
                            UID = "2bc84467-eace-42b5-b2c8-689c934f77df",
                            CreatedDate = new DateTime(2001, 5, 16, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7427),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 1,
                            Vendor = "INTEL"
                        },
                        new
                        {
                            UID = "38a56917-481b-4802-88ed-42c7f296f0af",
                            CreatedDate = new DateTime(2001, 5, 16, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7436),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 0,
                            Vendor = "AMD"
                        },
                        new
                        {
                            UID = "bd26d119-eea1-44c8-b9f0-47c2c0656ac3",
                            CreatedDate = new DateTime(2022, 3, 17, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7441),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 1,
                            Vendor = "ANDROID"
                        },
                        new
                        {
                            UID = "62a5f3cc-3201-4dc5-965a-4b6112779bd2",
                            CreatedDate = new DateTime(2022, 3, 17, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7446),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 1,
                            Vendor = "IPAD"
                        },
                        new
                        {
                            UID = "7955fb66-de2f-4bae-8556-09954820afb3",
                            CreatedDate = new DateTime(2001, 8, 18, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7451),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 0,
                            Vendor = "IPHONE 13"
                        },
                        new
                        {
                            UID = "1aa04704-59d7-4da2-b8b6-f91b5950512b",
                            CreatedDate = new DateTime(2014, 5, 16, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7457),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 1,
                            Vendor = "IPHONE XS"
                        },
                        new
                        {
                            UID = "98aaee50-e016-4238-8a98-b97ce10cdbb5",
                            CreatedDate = new DateTime(2012, 5, 16, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7462),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 1,
                            Vendor = "SURFACE PRO"
                        },
                        new
                        {
                            UID = "cd272b6f-a33d-46f5-b298-c1a883a9ed47",
                            CreatedDate = new DateTime(2012, 5, 16, 2, 3, 39, 890, DateTimeKind.Local).AddTicks(7468),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 0,
                            Vendor = "IMAC"
                        });
                });

            modelBuilder.Entity("ManageGateway.Domain.Models.Gateway", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SerialNumber");

                    b.ToTable("Gateways");

                    b.HasData(
                        new
                        {
                            SerialNumber = "DQzrzFZZ",
                            Address = "122.236.174.239",
                            Name = "Gateway1"
                        },
                        new
                        {
                            SerialNumber = "BGVCDTZA",
                            Address = "96.181.47.91",
                            Name = "Gateway2"
                        },
                        new
                        {
                            SerialNumber = "5jTocfWo",
                            Address = "169.32.116.241",
                            Name = "Gateway3"
                        },
                        new
                        {
                            SerialNumber = "5v3VqScu",
                            Address = "99.252.137.28",
                            Name = "Gateway4"
                        },
                        new
                        {
                            SerialNumber = "igDFAY6L",
                            Address = "241.232.209.216",
                            Name = "Gateway5"
                        });
                });

            modelBuilder.Entity("ManageGateway.Domain.Models.Device", b =>
                {
                    b.HasOne("ManageGateway.Domain.Models.Gateway", null)
                        .WithMany("Devices")
                        .HasForeignKey("GatewaySerialNumber");
                });

            modelBuilder.Entity("ManageGateway.Domain.Models.Gateway", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
