// <auto-generated />
using System;
using ManageGateway.Persistence.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManageGateway.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220317153113_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ManageGateway.Domain.Models.Device", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GatewaySerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UID");

                    b.HasIndex("GatewaySerialNumber");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            UID = "db52ad2c-a69c-4674-9523-ccb274b9c04b",
                            CreatedDate = new DateTime(2012, 3, 17, 11, 31, 13, 519, DateTimeKind.Local).AddTicks(9897),
                            GatewaySerialNumber = "DQzrzFZZ",
                            Status = 1,
                            Vendor = "IBM"
                        },
                        new
                        {
                            UID = "eef20c9d-8bb6-489f-9e2d-35ca002299bf",
                            CreatedDate = new DateTime(2001, 10, 17, 11, 31, 13, 519, DateTimeKind.Local).AddTicks(9936),
                            GatewaySerialNumber = "DQzrzFZZ",
                            Status = 1,
                            Vendor = "SAMSUNG"
                        },
                        new
                        {
                            UID = "79ef3d8a-96bc-4234-8d88-56e6892f84f2",
                            CreatedDate = new DateTime(2006, 9, 17, 11, 31, 13, 519, DateTimeKind.Local).AddTicks(9943),
                            GatewaySerialNumber = "DQzrzFZZ",
                            Status = 0,
                            Vendor = "APPLE"
                        },
                        new
                        {
                            UID = "99fb384a-a236-4cb4-8af3-0b5c40dfe88b",
                            CreatedDate = new DateTime(2001, 12, 17, 11, 31, 13, 519, DateTimeKind.Local).AddTicks(9950),
                            GatewaySerialNumber = "BGVCDTZA",
                            Status = 1,
                            Vendor = "MICROSOFT"
                        },
                        new
                        {
                            UID = "18223fd6-a17f-4cf0-8ed7-a97db9016c78",
                            CreatedDate = new DateTime(2010, 1, 17, 11, 31, 13, 519, DateTimeKind.Local).AddTicks(9955),
                            GatewaySerialNumber = "BGVCDTZA",
                            Status = 1,
                            Vendor = "XBOX"
                        },
                        new
                        {
                            UID = "2610f42c-e3d7-455f-968d-06bd0f7ccf53",
                            CreatedDate = new DateTime(2001, 10, 27, 11, 31, 13, 519, DateTimeKind.Local).AddTicks(9974),
                            GatewaySerialNumber = "BGVCDTZA",
                            Status = 0,
                            Vendor = "PLAY STATION"
                        },
                        new
                        {
                            UID = "b1c1c0c0-cd1f-49f9-b2fc-6d4515536230",
                            CreatedDate = new DateTime(1996, 7, 27, 11, 31, 13, 519, DateTimeKind.Local).AddTicks(9984),
                            GatewaySerialNumber = "BGVCDTZA",
                            Status = 1,
                            Vendor = "LENOVO"
                        },
                        new
                        {
                            UID = "3c8547bf-6045-4c6e-aa20-3b8f0370513c",
                            CreatedDate = new DateTime(2001, 10, 27, 11, 31, 13, 519, DateTimeKind.Local).AddTicks(9989),
                            GatewaySerialNumber = "BGVCDTZA",
                            Status = 1,
                            Vendor = "PANASONIC"
                        },
                        new
                        {
                            UID = "281d9fbd-a156-4baa-a9a8-0ff2ace67841",
                            CreatedDate = new DateTime(1998, 10, 18, 11, 31, 13, 519, DateTimeKind.Local).AddTicks(9995),
                            GatewaySerialNumber = "5jTocfWo",
                            Status = 0,
                            Vendor = "APPLE TV"
                        },
                        new
                        {
                            UID = "95537899-7235-4d85-83fe-fe75aa70400d",
                            CreatedDate = new DateTime(2019, 7, 18, 11, 31, 13, 520, DateTimeKind.Local),
                            GatewaySerialNumber = "5jTocfWo",
                            Status = 1,
                            Vendor = "APPLE WATCH"
                        },
                        new
                        {
                            UID = "1801348e-82d7-4889-877d-a618dfe7fef5",
                            CreatedDate = new DateTime(1996, 10, 27, 11, 31, 13, 520, DateTimeKind.Local).AddTicks(6),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 1,
                            Vendor = "HP"
                        },
                        new
                        {
                            UID = "66377769-f0ec-46f4-bac1-002b94adc5ce",
                            CreatedDate = new DateTime(2002, 2, 27, 11, 31, 13, 520, DateTimeKind.Local).AddTicks(12),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 0,
                            Vendor = "PRINTER"
                        },
                        new
                        {
                            UID = "815ae677-dd2b-4940-8384-fbab7a5e7e76",
                            CreatedDate = new DateTime(2011, 10, 27, 11, 31, 13, 520, DateTimeKind.Local).AddTicks(18),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 1,
                            Vendor = "HDD"
                        },
                        new
                        {
                            UID = "93567541-3e3c-4fb0-96f6-a7e709d68f0a",
                            CreatedDate = new DateTime(2001, 7, 2, 11, 31, 13, 520, DateTimeKind.Local).AddTicks(28),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 1,
                            Vendor = "SSD"
                        },
                        new
                        {
                            UID = "68655a0b-a355-490a-aaf1-49ec332c7c6b",
                            CreatedDate = new DateTime(2011, 1, 27, 11, 31, 13, 520, DateTimeKind.Local).AddTicks(33),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 0,
                            Vendor = "THOSIBA"
                        },
                        new
                        {
                            UID = "b041246c-66c5-4758-ac1d-69677c5b140b",
                            CreatedDate = new DateTime(2002, 8, 27, 11, 31, 13, 520, DateTimeKind.Local).AddTicks(48),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 1,
                            Vendor = "ACER"
                        },
                        new
                        {
                            UID = "cdfb4d07-219d-4742-8677-2d2d4dd85ebf",
                            CreatedDate = new DateTime(2001, 5, 16, 11, 31, 13, 520, DateTimeKind.Local).AddTicks(54),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 1,
                            Vendor = "INTEL"
                        },
                        new
                        {
                            UID = "5f1965cf-b7d2-4fb3-8965-91c31d7ee8c4",
                            CreatedDate = new DateTime(2001, 5, 16, 11, 31, 13, 520, DateTimeKind.Local).AddTicks(60),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 0,
                            Vendor = "AMD"
                        },
                        new
                        {
                            UID = "6d37d556-06f7-4b96-bb8e-cca16e940cf6",
                            CreatedDate = new DateTime(2022, 3, 17, 11, 31, 13, 520, DateTimeKind.Local).AddTicks(65),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 1,
                            Vendor = "ANDROID"
                        },
                        new
                        {
                            UID = "9d92e86e-a14b-47ea-8013-9953cc6a4b6a",
                            CreatedDate = new DateTime(2022, 3, 17, 11, 31, 13, 520, DateTimeKind.Local).AddTicks(70),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 1,
                            Vendor = "IPAD"
                        },
                        new
                        {
                            UID = "8f97b005-b9eb-478f-b585-14966dc40cf2",
                            CreatedDate = new DateTime(2001, 8, 18, 11, 31, 13, 520, DateTimeKind.Local).AddTicks(74),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 0,
                            Vendor = "IPHONE 13"
                        },
                        new
                        {
                            UID = "99d06cc3-a7af-4fd8-a43c-f306e147bc88",
                            CreatedDate = new DateTime(2014, 5, 16, 11, 31, 13, 520, DateTimeKind.Local).AddTicks(82),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 1,
                            Vendor = "IPHONE XS"
                        },
                        new
                        {
                            UID = "6cc202db-2539-4efd-97f1-dc18df4db13d",
                            CreatedDate = new DateTime(2012, 5, 16, 11, 31, 13, 520, DateTimeKind.Local).AddTicks(88),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 1,
                            Vendor = "SURFACE PRO"
                        },
                        new
                        {
                            UID = "3cc16475-42b7-44d8-9f36-3685bceefb13",
                            CreatedDate = new DateTime(2012, 5, 16, 11, 31, 13, 520, DateTimeKind.Local).AddTicks(94),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 0,
                            Vendor = "IMAC"
                        });
                });

            modelBuilder.Entity("ManageGateway.Domain.Models.Gateway", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SerialNumber");

                    b.ToTable("Gateways");

                    b.HasData(
                        new
                        {
                            SerialNumber = "DQzrzFZZ",
                            Address = "122.236.174.239",
                            Name = "Gateway1"
                        },
                        new
                        {
                            SerialNumber = "BGVCDTZA",
                            Address = "96.181.47.91",
                            Name = "Gateway2"
                        },
                        new
                        {
                            SerialNumber = "5jTocfWo",
                            Address = "169.32.116.241",
                            Name = "Gateway3"
                        },
                        new
                        {
                            SerialNumber = "5v3VqScu",
                            Address = "99.252.137.28",
                            Name = "Gateway4"
                        },
                        new
                        {
                            SerialNumber = "igDFAY6L",
                            Address = "241.232.209.216",
                            Name = "Gateway5"
                        });
                });

            modelBuilder.Entity("ManageGateway.Domain.Models.Device", b =>
                {
                    b.HasOne("ManageGateway.Domain.Models.Gateway", null)
                        .WithMany("Devices")
                        .HasForeignKey("GatewaySerialNumber");
                });

            modelBuilder.Entity("ManageGateway.Domain.Models.Gateway", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
