// <auto-generated />
using System;
using ManageGateway.Persistence.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManageGateway.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ManageGateway.Domain.Models.Device", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GatewaySerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UID");

                    b.HasIndex("GatewaySerialNumber");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            UID = "4e24c3be-a634-4388-9002-2f6b4405b655",
                            CreatedDate = new DateTime(2020, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "DQzrzFZZ",
                            Status = 0,
                            Vendor = "IBM"
                        },
                        new
                        {
                            UID = "e4ea378c-f99a-482e-ac44-2ae7db111bf0",
                            CreatedDate = new DateTime(2008, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "DQzrzFZZ",
                            Status = 0,
                            Vendor = "SAMSUNG"
                        },
                        new
                        {
                            UID = "f5fe8ce4-4b58-45ab-a802-f14989f8c9f3",
                            CreatedDate = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "DQzrzFZZ",
                            Status = 1,
                            Vendor = "APPLE"
                        },
                        new
                        {
                            UID = "540b1edb-0bc2-4cde-94c2-748df32bd1e6",
                            CreatedDate = new DateTime(2020, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "BGVCDTZA",
                            Status = 0,
                            Vendor = "MICROSOFT"
                        },
                        new
                        {
                            UID = "0f66a4b2-85b3-4757-b1c5-039acf6b3c5d",
                            CreatedDate = new DateTime(2008, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "BGVCDTZA",
                            Status = 0,
                            Vendor = "XBOX"
                        },
                        new
                        {
                            UID = "f0606a1f-eb6d-4357-adbf-0ad765700465",
                            CreatedDate = new DateTime(2018, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "BGVCDTZA",
                            Status = 1,
                            Vendor = "PLAY STATION"
                        },
                        new
                        {
                            UID = "28d0151c-880b-4929-bd22-aacd07a24b06",
                            CreatedDate = new DateTime(2009, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "BGVCDTZA",
                            Status = 0,
                            Vendor = "LENOVO"
                        },
                        new
                        {
                            UID = "8666dbc0-5e18-44bd-8f40-e96fa020afaa",
                            CreatedDate = new DateTime(2018, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "BGVCDTZA",
                            Status = 0,
                            Vendor = "PANASONIC"
                        },
                        new
                        {
                            UID = "75cee42e-fc2f-45db-9ccc-e785af14bba6",
                            CreatedDate = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "5jTocfWo",
                            Status = 1,
                            Vendor = "APPLE TV"
                        },
                        new
                        {
                            UID = "c3c182d2-854f-4555-8b82-76a87a115aa6",
                            CreatedDate = new DateTime(2020, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "5jTocfWo",
                            Status = 0,
                            Vendor = "APPLE WATCH"
                        },
                        new
                        {
                            UID = "1eda5082-72be-4982-93fd-bd8a729d3391",
                            CreatedDate = new DateTime(2008, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 0,
                            Vendor = "HP"
                        },
                        new
                        {
                            UID = "368436d2-6629-443a-a039-cb130a0ea529",
                            CreatedDate = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 1,
                            Vendor = "PRINTER"
                        },
                        new
                        {
                            UID = "62f4e2e9-3a72-4083-88f1-eb821b436d3b",
                            CreatedDate = new DateTime(2020, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 0,
                            Vendor = "HDD"
                        },
                        new
                        {
                            UID = "e4c13cf3-006c-40ab-91da-d2924ecf11c3",
                            CreatedDate = new DateTime(2008, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 0,
                            Vendor = "SSD"
                        },
                        new
                        {
                            UID = "863ed4bd-7294-406a-aec5-731dabe5b704",
                            CreatedDate = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 1,
                            Vendor = "THOSIBA"
                        },
                        new
                        {
                            UID = "8362becf-84d5-4914-9ed9-dc818c01770b",
                            CreatedDate = new DateTime(2020, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 0,
                            Vendor = "ACER"
                        },
                        new
                        {
                            UID = "8e309713-e9b4-449d-a039-1781b7d8642f",
                            CreatedDate = new DateTime(2008, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "5v3VqScu",
                            Status = 0,
                            Vendor = "INTEL"
                        },
                        new
                        {
                            UID = "b587f427-01cb-4e5e-b0c1-9cfa914eab61",
                            CreatedDate = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 1,
                            Vendor = "AMD"
                        },
                        new
                        {
                            UID = "094d23bf-a700-40de-945b-b6419a936085",
                            CreatedDate = new DateTime(2020, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 0,
                            Vendor = "ANDROID"
                        },
                        new
                        {
                            UID = "83b7e031-d4d9-41a3-9e12-f0ff080e367a",
                            CreatedDate = new DateTime(2008, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 0,
                            Vendor = "IPAD"
                        },
                        new
                        {
                            UID = "4726f25f-cee8-4905-bfd9-9e3bebdda731",
                            CreatedDate = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 1,
                            Vendor = "IPHONE 13"
                        },
                        new
                        {
                            UID = "c103fede-a624-4281-9c70-3b3dc2ebdee3",
                            CreatedDate = new DateTime(2020, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 0,
                            Vendor = "IPHONE XS"
                        },
                        new
                        {
                            UID = "c80dcf46-5d21-4f2a-b5a8-ecdc2911aa69",
                            CreatedDate = new DateTime(2018, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 0,
                            Vendor = "SURFACE PRO"
                        },
                        new
                        {
                            UID = "2afb4b53-1315-495c-88c1-441257418db0",
                            CreatedDate = new DateTime(2021, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatewaySerialNumber = "igDFAY6L",
                            Status = 1,
                            Vendor = "IMAC"
                        });
                });

            modelBuilder.Entity("ManageGateway.Domain.Models.Gateway", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SerialNumber");

                    b.ToTable("Gateways");

                    b.HasData(
                        new
                        {
                            SerialNumber = "DQzrzFZZ",
                            Address = "122.236.174.239",
                            Name = "Gateway1"
                        },
                        new
                        {
                            SerialNumber = "BGVCDTZA",
                            Address = "96.181.47.91",
                            Name = "Gateway2"
                        },
                        new
                        {
                            SerialNumber = "5jTocfWo",
                            Address = "169.32.116.241",
                            Name = "Gateway3"
                        },
                        new
                        {
                            SerialNumber = "5v3VqScu",
                            Address = "99.252.137.28",
                            Name = "Gateway4"
                        },
                        new
                        {
                            SerialNumber = "igDFAY6L",
                            Address = "241.232.209.216",
                            Name = "Gateway5"
                        });
                });

            modelBuilder.Entity("ManageGateway.Domain.Models.Device", b =>
                {
                    b.HasOne("ManageGateway.Domain.Models.Gateway", "Gateway")
                        .WithMany("Devices")
                        .HasForeignKey("GatewaySerialNumber");

                    b.Navigation("Gateway");
                });

            modelBuilder.Entity("ManageGateway.Domain.Models.Gateway", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
